backend:
  name: github
  repo: dvsrshohan/gatsby
  open_authoring: true
      auth_endpoint: '/api/auth'
      always_fork: true
  branch: main
  base_url: '/api/v1'

media_folder: public/images
public_folder: /images

collections:
  - name: jobs
    label: Jobs
    folder: src/jobs
    create: true
    fields:
      - { name: id, label: Id }
      - { name: publishData, label: PublishData, widget: datetime }
      - { name: title, label: Title ,widget: string}
      - { name: team, label: Team ,widget: string}
      - { name: price, label: Price }
      - { name: salaryClass, label: SalaryClass ,widget: string}
      - { name: location, label: Location }
      - { name: locationArea, label: LocationArea ,widget: string}
      - { name: member, label: Member ,widget: string}
      - { name: experience, label: Experience,widget: string }
      - { name: aboutCompany, label: AboutCompany,widget: string }
      - { name: admin, label: Admin }
      - { name: tittleImg, label: TittleImg ,widget: image}
      - { name: logo, label: Logo ,widget: image}
      - { name: body, label: Body, widget: markdown }